---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
```


For the first analysis I want to compare the increase year on year on sales with the increase in price.

```{r}
(var_price_revenue <- fundamentals %>% select(ticker = `Ticker Symbol`,period = `Period Ending`,total_revenue = `Total Revenue`) %>%
  left_join(prices,by=c("ticker" = "symbol","period" = "date")) %>% 
  select(ticker,period,total_revenue,price = close) %>% 
  group_by(ticker) %>% 
  mutate(var_revenue = total_revenue / lag(total_revenue) - 1,
         var_price = price / lag(price) - 1))
```

```{r message=FALSE,warning=FALSE}
ggplot(var_price_revenue)+
  geom_point(aes(x=var_revenue,y=var_price),alpha=0.3,color="#4B86B4")+
  coord_cartesian(xlim = c(-0.5,0.5))+
  theme_minimal()+
  geom_smooth(aes(x=var_revenue,y=var_price),method="lm")
```
```{r}
broom::tidy(summary(lm(var_price_revenue$var_price~var_price_revenue$var_revenue)))
```
```{r message=FALSE,warning=FALSE}
prices_sector <- var_price_revenue %>% inner_join(securities,by = c("ticker" = "Ticker symbol")) %>% 
  select(ticker,var_price,sector = `GICS Sector`)

ggplot(prices_sector)+
  geom_boxplot(aes(x=sector,y=var_price,fill=(sector == "Information Technology")),alpha=0.6)+
  geom_jitter(aes(x=sector,y=var_price),alpha=0.6,color="#4B86B4")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1),legend.position="none")
```

